[package]
name = "j-rss-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.6", default-features = false, features = ["rustls-tls"] }
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
anyhow = "1.0"
